//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.34209
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

public class Dialogue
{
	public int id;

	public List<Statement> dialogueList;

	public Dialogue ()
	{
		dialogueList = new List<Statement> ();
	}

	public Dialogue (int Id, List<Statement> statements)
	{
		id = Id;
		dialogueList = statements;
	}

	public class Statement
	{
		public string person;
		public string text;
	}
}